[[block]]
block = "focused_window"
max_width = 135

[[block]]
block = "net"
device = "enp0s25"
# ip = false
interval = 5
# icons_format = "{icon} "
# signal_strength = true
format = "{speed_down;K*b} {speed_up;K*b}"

[[block]]
block = "load"
interval = 5
format = "{1m} {5m} {15m}"

[[block]]
block = "disk_space"
path = "/home"
info_type = "available"
warning = 32.0
alert = 16.0
interval = 90
unit = "GB"
alert_absolute = true

[[block]]
block = "maildir"
interval = 15
inboxes = ["/home/rkumar/mail/seirdy/Inbox"]
threshold_warning = 1
threshold_critical = 10
display_type = "new"

[[block]]
block = "time"
format = "%a %d %R%z"
[[block]]
block = "time"
format = "%R%z"
timezone = "Etc/UTC"
