# font = "monospace term"
# icons  = "material-nf"
# theme="slick"

[icons]
name = "material-nf"
[icons.overrides]
music = "  "
# time = " "
net_wired = ""
net_up = '祝'
net_down = ''
net_vpn = " "
music_play = " 契"
music_pause = " "
music_prev = " 玲"
music_next = " 怜"
disk_drive = " "

[theme]
name="slick"
[theme.overrides]
# separator=""
idle_bg = "#232629"

# [[block]]
# block = "music"
# format = "$combo.rot_str(30) $play $next"
# player = ["mpd"]
# hide_when_empty = true
# buttons = ["play", "next"]
# max_width=35
#smart_trim = true
#dynamic_width = true
#marquee=false

# [[block]]
# block = "bluetooth"
# mac = "BC:F2:92:28:14:65"
# format = "{percentage}%"
# hide_disconnected = true
