[[block]]
block = "focused_window"
max_width = 60

[[block]]
block = "battery"
driver = "upower"
format = "{percentage}%"

[[block]]
block="net"
device = "wlo1"
signal_strength = true
use_bits = true
interval = 3

[[block]]
block = "maildir"
inboxes = ["~/mail/seirdy"]
interval = 300
display_type = "new"

[[block]]
block = "time"
format = "%m-%d %H:%M"
