[[block]]
block = "focused_window"
max_width = 135

[[block]]
block = "net"
device = "wlp3s0"
ip = false
interval = 3
signal_strength = true
use_bits = true

[[block]]
block = "load"
interval = 5
format = "{1m} {5m} {15m}"

[[block]]
block = "notmuch"
maildir = "/home/rkumar/mail"
query = "tag:unread folder:seirdy/Inbox and not tag:archived"
threshold_good = 1
threshold_info = 3
threshold_warning = 5
threshold_critical = 10
interval = 30

[[block]]
block = "notmuch"
maildir = "/home/rkumar/mail"
query = "tag:unread folder:school/Inbox and not tag:archived"
threshold_good = 1
threshold_info = 5
threshold_warning = 8
threshold_critical = 15
interval = 30

[[block]]
block = "time"
format = "%a %m-%d %R%:z"
