font = "monospace term"

[icons]
name = "material-nf"
[icons.overrides]
music = "  "
# time = " "
net_wired = ""
net_up = '祝'
net_down = ' '
net_vpn = " "
music_play = " 契"
music_pause = " "
music_prev = " 玲"
music_next = " 怜"

[theme]
name="slick"
[theme.overrides]
# separator=""
idle_bg = "#232629"

[[block]]
block = "music"
player = "mpd"
buttons = ["play", "next"]
max_width=35
smart_trim = true
dynamic_width = true
marquee=false

[[block]]
block = "bluetooth"
mac = "BC:F2:92:28:14:65"
label = ""
hide_disconnected = true
