font = "Hasklug Nerd Font"

[icons]
name = "awesome"
[icons.overrides]
music = " "
time = " "

[theme]
name="slick"
[theme.overrides]
idle_bg = "#232629"

[[block]]
block = "focused_window"
max_width = 100

[[block]]
block = "battery"
driver = "upower"
format = "{percentage}%"

[[block]]
block = "sound"
driver = "pulseaudio"
on_click = "pavucontrol-qt"

[[block]]
block = "music"
buttons = ["play", "next"]

[[block]]
block="net"
device = "wlo1"
signal_strength = true
interval = 3

[[block]]
block = "time"
format = "%m-%d %H:%M"
