[[block]]
block = "focused_window"
max_width = 135

[[block]]
block = "net"
device = "wlp3s0"
ip = false
interval = 3
signal_strength = true
use_bits = true

[[block]]
block = "load"
interval = 5
format = "{1m} {5m} {15m}"

[[block]]
block = "notmuch"
maildir = "/home/rkumar/mail"
query = "tag:Inbox tag:unread folder:seirdy/Inbox and not tag:archived"
threshold_good = 0
threshold_info = 1
threshold_warning = 3
threshold_critical = 5
interval = 300

[[block]]
block = "notmuch"
maildir = "/home/rkumar/mail"
query = "tag:Inbox tag:unread folder:school/Inbox and not tag:archived"
threshold_good = 10
threshold_info = 30
threshold_warning = 70
threshold_critical = 90
interval = 150

[[block]]
block = "time"
format = "%a %m-%d %R%:z"
