[[block]]
block = "focused_window"
driver = "wlr_toplevel_management"
format = " $title.str(max_w:120)| "

[[block]]
block = "net"
device = "^enp[0-9]"
# ip = false
interval = 3
# icons_format = "{icon} "
# signal_strength = true
format = " $icon $speed_down.eng(prefix:K) $speed_up.eng(prefix:K) "

[[block]]
block = "load"
interval = 5
format = " $1m.eng(w:3) $5m.eng(w:3) $15m.eng(w:3) "

[[block]]
block = "disk_space"
path = "/home"
info_type = "available"
warning = 20.0
alert = 10.0
interval = 90
#unit = "GB"

[[block]]
block = "maildir"
interval = 15
inboxes = ["/home/rkumar/mail/seirdy/Inbox"]
threshold_warning = 1
threshold_critical = 10
display_type = "new"

[[block]]
block = "time"
format = " $timestamp.datetime(f:'%a %d %R%z') "
[[block]]
block = "time"
format = " $timestamp.datetime(f:'%R%z') "
timezone = "Etc/UTC"
