[[block]]
block = "focused_window"
max_width = 135

[[block]]
block = "net"
device = "enp0s25"
ip = false
interval = 5
signal_strength = true
use_bits = true

[[block]]
block = "load"
interval = 5
format = "{1m} {5m} {15m}"

[[block]]
block = "maildir"
interval = 30
inboxes = ["/home/rkumar/mail/seirdy/Inbox"]
threshold_warning = 1
threshold_critical = 10
display_type = "new"

[[block]]
block = "time"
format = "%a %m-%d %R%:z"
