[[block]]
block = "focused_window"
max_width = 100

[[block]]
block = "battery"
driver = "upower"
format = "{percentage}%"

[[block]]
block="net"
device = "wlo1"
signal_strength = true
interval = 3

[[block]]
block = "time"
format = "%m-%d %H:%M"
