[[block]]
block = "focused_window"
max_width = 135

[[block]]
block = "net"
device = "enp8s0u1"
ip = false
interval = 5

[[block]]
block = "load"
interval = 5
format = "{1m} {5m} {15m}"

[[block]]
block = "time"
format = "%a %m-%d %R%:z"
