[[block]]
block = "focused_window"
[block.format]
full = "$title.str(30)|"
#short = "$title.rot-str(20)|"

[[block]]
block = "net"
device = "enp0s25"
# ip = false
interval = 3
# icons_format = "{icon} "
# signal_strength = true
format = "$speed_down.eng(3,B,K)$speed_up.eng(3,B,K)"

[[block]]
block = "load"
interval = 5
format = "$1m.eng(3) $5m.eng(3) $15m.eng(3)"

[[block]]
block = "disk_space"
path = "/home"
info_type = "available"
warning = 20.0
alert = 10.0
interval = 90
#unit = "GB"

[[block]]
block = "maildir"
interval = 15
inboxes = ["/home/rkumar/mail/seirdy/Inbox"]
threshold_warning = 1
threshold_critical = 10
display_type = "new"

[[block]]
block = "time"
format = "%a %d %R%z"
[[block]]
block = "time"
format = "%R%z"
timezone = "Etc/UTC"
