[[block]]
block = "focused_window"
max_width = 60

[[block]]
block = "battery"
driver = "upower"
format = "{percentage}%"

[[block]]
block="net"
device = "wlo1"
signal_strength = true
use_bits = true
interval = 3

[[block]]
block = "notmuch"
maildir = "/home/rkumar/mail"
query = "tag:unread folder:seirdy/Inbox and not tag:archived"
threshold_good = 1
threshold_info = 3
threshold_warning = 5
threshold_critical = 10
interval = 30

[[block]]
block = "notmuch"
maildir = "/home/rkumar/mail"
query = "tag:unread folder:school/Inbox and not tag:archived"
threshold_good = 1
threshold_info = 5
threshold_warning = 8
threshold_critical = 15
interval = 30

[[block]]
block = "time"
format = "%m-%d %H:%M"
