[[block]]
block = "focused_window"
max_width = 135

[[block]]
block = "net"
device = "wlp3s0"
ip = false
interval = 3
signal_strength = true
use_bits = true

[[block]]
block = "load"
interval = 5
format = "{1m} {5m} {15m}"

[[block]]
block = "maildir"
inboxes = ["~/mail/seirdy"]
interval = 300
display_type = "new"

[[block]]
block = "time"
format = "%a %m-%d %R%:z"
