[[block]]
block = "focused_window"
max_width = 60

[[block]]
block = "battery"
driver = "upower"
format = "{percentage}%"

[[block]]
block="net"
device = "wlp0s20u3u4"
signal_strength = true
use_bits = true
interval = 3

[[block]]
block = "maildir"
interval = 30
inboxes = ["/home/rkumar/mail/seirdy/Inbox"]
threshold_warning = 1
threshold_critical = 10
display_type = "new"

# [[block]]
# block = "notmuch"
# maildir = "/home/rkumar/mail"
# query = "tag:unread folder:seirdy/Inbox and not tag:archived"
# threshold_good = 1
# threshold_info = 3
# threshold_warning = 5
# threshold_critical = 10
# interval = 30

[[block]]
block = "time"
format = "%m-%d %H:%M"
