[[block]]
block = "focused_window"
max_width = 65

[[block]]
block = "battery"
driver = "upower"
format = "{percentage}%"

[[block]]
block = "net"
# device = "enp0s25"
# ip = false
interval = 5
# icons_format = "{icon} "
# signal_strength = true
format = "{signal_strength}"

[[block]]
block = "maildir"
interval = 25
inboxes = ["~/mail/seirdy/Inbox"]
threshold_warning = 1
threshold_critical = 10
display_type = "new"

# [[block]]
# block = "notmuch"
# maildir = "/home/rkumar/mail"
# query = "tag:unread folder:seirdy/Inbox and not tag:archived"
# threshold_good = 1
# threshold_info = 3
# threshold_warning = 5
# threshold_critical = 10
# interval = 30

[[block]]
block = "time"
format = "%m-%d %H:%M"
