#!/bin/sh
# aerc filter which runs w3m using firejail to prevent
# any phoning home by rendered emails
exec firejail --noprofile --net=none --caps.drop=all w3m \
	-T text/html \
	-cols $(tput cols) \
	-dump \
	-o display_image=false \
	-o display_link_number=true
