#!/bin/sh

mkdir -p "$HOME/Executables" || exit
# shellcheck disable=2164
cd "$HOME/Executables"
mkdir -p 'go/bin' 'pipx/bin' 'gem/bin' 'luarocks/bin' 'npm/bin' 'cargo/bin' 'stack/bin' "$HOME/bootstrap-logs"
# shellcheck disable=2164
cd "$HOME"
# shellcheck disable=2016
echo 'Created some directories before adding to $PATH'
if [ -z "$PROFILE_SET" ]; then
	# shellcheck source=../../.profile
	. "$HOME/.profile"
	export PROFILE_SET=2
	# make sure all the variables were set in .profile
	[ "$GOPATH" = "$HOME/Executables/go" ] || exit 1
fi
echo "Running bootstrap for $MACHINE"

bootstrap_dir="$HOME/Executables/shell-scripts/bootstrap"
updates_dir="$HOME/Executables/shell-scripts/updates"

# TODO: Add support for FreeBSD (TrueOS with Area51 repo)
if [ "$MACHINE" = 'Linux' ]; then
	if [ -f /usr/lib/os-release ]; then
		echo 'Detected Linux'
		# my scripts only work on Fedora atm. TODO: add support for Debian
		# shellcheck source=/dev/null
		. /usr/lib/os-release
		if [ "$NAME" = 'Fedora' ]; then
			echo 'Installing dnf packages for Fedora'
			sudo bash "$bootstrap_dir/sudo-dnf.sh" | tee "$HOME/bootstrap-logs/dnf.log"
		fi
		nohup dash "$bootstrap_dir/flatpak.sh" >"$HOME/bootstrap-logs/flatpak.log" &
		nohup dash "$updates_dir/chromium.sh" >"$HOME/bootstrap-logs/chromium.log" &
	fi
elif [ "$MACHINE" = 'Darwin' ]; then
	echo 'Installing homebrew packages'
	bash "$bootstrap_dir/homebrew-install.sh"
else
	echo 'Unrecognized OS.'
	exit
fi

dash "$bootstrap_dir/cargo.sh" >"$HOME/bootstrap-logs/cargo.log" &

gem pristine msgpack
gem install neovim

dash "$bootstrap_dir/zplugin.sh" >"$HOME/bootstrap-logs/zplugin.log" 2>&1 &
dash "$updates_dir/node.sh" >"$HOME/bootstrap-logs/node.log" 2>&1 &
dash "$updates_dir/stack.sh" >"$HOME/bootstrap-logs/stack.log" 2>&1 &
dash "$updates_dir/go.sh" >"$HOME/bootstrap-logs/go.log" 2>&1 &
dash "$updates_dir/kitty.sh" >"$HOME/bootstrap-logs/kitty.log" 2>&1 &
# Install pynvim before building neovim
dash "$bootstrap_dir/python.sh" >"$HOME/bootstrap-logs/python.log" 2>&1
dash "$updates_dir/neovim.sh" >"$HOME/bootstrap-logs/neovim.log" 2>&1 &
# install conmon before building runc, podman, buildah, skopeo
dash "$updates_dir/small-cc-programs.sh" >"$HOME/bootstrap-logs/small-cc-programs.log" 2>&1
dash "$updates_dir/go-big.sh" >"$HOME/bootstrap-logs/go-big.log" 2>&1
echo 'Bootstrap executed! Some tasks might still be running in the background'
echo "Check out $HOME/bootstrap-logs/ for logs"
echo 'When everything looks done, reboot and run "update-all" to make sure everything worked'
