#!/bin/zsh
# powerlevel9k
export POWERLEVEL9K_GITSTATUS_DIR="$ZPLGM[PLUGINS_DIR]/romkatv---powerlevel10k/gitstatus"
POWERLEVEL9K_DEFAULT_BACKGROUND='black'
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
	dir_writable dir anaconda virtualenv vcs newline vi_mode status
)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
	newline root_indicator background_jobs history command_execution_time time
)
POWERLEVEL9K_SHORTEN_STRATEGY='truncate_from_right'
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_MODE='nerdfont-complete'
# POWERLEVEL9K_MODE="awesome-fontconfig"
POWERLEVEL9K_RPROMPT_ON_NEWLINE=false
# right prompt colors
POWERLEVEL9K_TIME_BACKGROUND='blue'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND='012' # light blue
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='black'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=0.5
POWERLEVEL9K_HISTORY_BACKGROUND='cyan'
POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND='black' # light cyan
# powerlevel9k icons
POWERLEVEL9K_SHORTEN_DELIMITER=''
POWERLEVEL9K_HOME_ICON=$'\uf7db'     # 
POWERLEVEL9K_HOME_SUB_ICON=$'\uf74a' # 
POWERLEVEL9K_FOLDER_ICON=$'\uf74f'   #  ﱮ
POWERLEVEL9K_VI_INSERT_MODE_STRING=$'\uf8ea'
POWERLEVEL9K_VI_COMMAND_MODE_STRING=$'\uf8ee'
# VCS icons
POWERLEVEL9K_VCS_GIT_ICON=$'\uf1d2 '
POWERLEVEL9K_VCS_GIT_GITHUB_ICON=$'\uf113 '
POWERLEVEL9K_VCS_GIT_GITLAB_ICON=$'\uf296 '
POWERLEVEL9K_VCS_BRANCH_ICON=$'\ue725 '
POWERLEVEL9K_VCS_STAGED_ICON=$'\uf055'
POWERLEVEL9K_VCS_UNSTAGED_ICON=$'\uf421'
POWERLEVEL9K_VCS_UNTRACKED_ICON=$'\uf00d'
POWERLEVEL9K_VCS_STASH_ICON=$'\uf140 '
POWERLEVEL9K_VCS_MODIFIED_ICON=$'\uf192'
POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON=$'\uf0ab '
POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON=$'\uf0aa '
POWERLEVEL9K_SHOW_CHANGESET="true"
POWERLEVEL9K_CHANGESET_HASH_LENGTH="8"
# anaconda
POWERLEVEL9K_ANACONDA_BACKGROUND='cyan'
POWERLEVEL9K_ANACONDA_LEFT_DELIMITER=''
POWERLEVEL9K_ANACONDA_RIGHT_DELIMITER=''
# powerlevel9k status icons
POWERLEVEL9K_OK_ICON=$'\uf054'

# Remove some icons
POWERLEVEL9K_TIME_ICON=
POWERLEVEL9K_EXECUTION_TIME_ICON=
