---
tools:
  # linters
  markdown-markdownlint: &markdown-markdownlint
    lint-command: 'markdownlint -c ~/.config/markdownlint/markdownlint.json -s'
    lint-stdin: true
    lint-formats:
      - '%f:%l: %m'
      - '%f:%l:%c %m'
  rst-lint: &rst-lint
    lint-command: 'rst-lint'
    lint-stdin: false
    lint-formats:
      - '%tNFO %f:%l %m'
      - '%tARNING %f:%l %m'
      - '%tRROR %f:%l %m'
      - '%tEVERE %f:%l %m'
  vim-vint: &vim-vint
    lint-command: 'vint'
    lint-formats:
      - '%f:%l:%c: %m'
  make-checkmake: &make-checkmake
    lint-command: 'checkmake'
    lint-stdin: true
  sh-shellcheck: &sh-shellcheck
    lint-command: 'shellcheck -f gcc -xa -o all -e SC2250'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'
  python-flake8: &python-flake8
    lint-command: '~/Executables/pipx/bin/flake8 --stdin-display-name ${INPUT} -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'
  dockerfile-hadolint: &dockerfile-hadolint
    lint-command: 'hadolint'
    lint-formats:
      - '%f:%l %m'
  yaml-yamllint: &yaml-yamllint
    lint-command: 'yamllint -f parsable -'
    lint-stdin: true
  # formatters
  rst-pandoc: &rst-pandoc
    format-command: 'pandoc -f rst -t rst -s --columns=79'
  sh-shfmt: &sh-shfmt
    format-command: 'shfmt -ci -s -bn'
    format-stdin: true

languages:
  pandoc:
    - <<: *markdown-markdownlint
  markdown:
    - <<: *markdown-markdownlint
  gfm:
    - <<: *markdown-markdownlint
  python:
    - <<: *python-flake8
  rst:
    - <<: *rst-lint
    - <<: *rst-pandoc
  sh:
    - <<: *sh-shellcheck
    - <<: *sh-shfmt
  vim:
    - <<: *vim-vint
  make:
    - <<: *make-checkmake
  yaml:
    - <<: *yaml-yamllint
  dockerfile:
    - <<: *dockerfile-hadolint
---
